# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcula.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pyperclip
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 640)
        font = QtGui.QFont()
        font.setPointSize(26)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.answer = QtWidgets.QLabel(self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(0, 80, 380,100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(34)
        font.setBold(False)
        font.setWeight(50)
        self.answer.setFont(font)
        self.answer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.answer.setAutoFillBackground(False)
        self.answer.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 15px;\n"
"text-align: right;\n"
"text-align: right;")
        self.answer.setObjectName("answer")
        self.AC = QtWidgets.QPushButton(self.centralwidget)
        self.AC.setGeometry(QtCore.QRect(20, 190, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.AC.setFont(font)
        self.AC.setStyleSheet("border-radius: 35px;\n"
"background-color: rgb(170, 170, 170);\n"
"")
        self.AC.setObjectName("AC")
        self.copy = QtWidgets.QPushButton(self.centralwidget)
        self.copy.setGeometry(QtCore.QRect(110, 190, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.copy.setFont(font)
        self.copy.setStyleSheet("border-radius: 35px;\n"
"background-color: rgb(170, 170, 170);\n"
"")
        self.copy.setObjectName("copy")
        self.delete = QtWidgets.QPushButton(self.centralwidget)
        self.delete.setGeometry(QtCore.QRect(200, 190, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.delete.setFont(font)
        self.delete.setStyleSheet("border-radius: 35px;\n"
"background-color: rgb(170, 170, 170);\n"
"")
        self.delete.setObjectName("delete")
        self.share = QtWidgets.QPushButton(self.centralwidget)
        self.share.setGeometry(QtCore.QRect(290, 190, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        self.share.setFont(font)
        self.share.setStyleSheet("border-radius: 35px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom: 10px;")
        self.share.setObjectName("share")
        self.mul = QtWidgets.QPushButton(self.centralwidget)
        self.mul.setGeometry(QtCore.QRect(290, 280, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.mul.setFont(font)
        self.mul.setStyleSheet("border-radius: 35px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom: 10px;")
        self.mul.setObjectName("mul")
        self.c9 = QtWidgets.QPushButton(self.centralwidget)
        self.c9.setGeometry(QtCore.QRect(200, 280, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.c9.setFont(font)
        self.c9.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"")
        self.c9.setObjectName("c9")
        self.c7 = QtWidgets.QPushButton(self.centralwidget)
        self.c7.setGeometry(QtCore.QRect(20, 280, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.c7.setFont(font)
        self.c7.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"")
        self.c7.setObjectName("c7")
        self.c8 = QtWidgets.QPushButton(self.centralwidget)
        self.c8.setGeometry(QtCore.QRect(110, 280, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.c8.setFont(font)
        self.c8.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"")
        self.c8.setObjectName("c8")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(290, 370, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.minus.setFont(font)
        self.minus.setStyleSheet("border-radius: 35px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom: 10px;")
        self.minus.setObjectName("minus")
        self.c6 = QtWidgets.QPushButton(self.centralwidget)
        self.c6.setGeometry(QtCore.QRect(200, 370, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.c6.setFont(font)
        self.c6.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"")
        self.c6.setObjectName("c6")
        self.c4 = QtWidgets.QPushButton(self.centralwidget)
        self.c4.setGeometry(QtCore.QRect(20, 370, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.c4.setFont(font)
        self.c4.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"")
        self.c4.setObjectName("c4")
        self.c5 = QtWidgets.QPushButton(self.centralwidget)
        self.c5.setGeometry(QtCore.QRect(110, 370, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.c5.setFont(font)
        self.c5.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"")
        self.c5.setObjectName("c5")
        self.equ = QtWidgets.QPushButton(self.centralwidget)
        self.equ.setGeometry(QtCore.QRect(290, 550, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.equ.setFont(font)
        self.equ.setStyleSheet("border-radius: 35px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom: 10px;")
        self.equ.setObjectName("equ")
        self.comma = QtWidgets.QPushButton(self.centralwidget)
        self.comma.setGeometry(QtCore.QRect(200, 550, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.comma.setFont(font)
        self.comma.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"")
        self.comma.setObjectName("comma")
        self.c0 = QtWidgets.QPushButton(self.centralwidget)
        self.c0.setGeometry(QtCore.QRect(20, 550, 160, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.c0.setFont(font)
        self.c0.setStyleSheet("border-radius: 35px;\n"
"text-align: left;\n"
"padding-left: 29px;\n"
"background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.c0.setObjectName("c0")
        self.c1 = QtWidgets.QPushButton(self.centralwidget)
        self.c1.setGeometry(QtCore.QRect(20, 460, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.c1.setFont(font)
        self.c1.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"")
        self.c1.setObjectName("c1")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(290, 460, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.plus.setFont(font)
        self.plus.setStyleSheet("border-radius: 35px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom: 10px;")
        self.plus.setObjectName("plus")
        self.c2 = QtWidgets.QPushButton(self.centralwidget)
        self.c2.setGeometry(QtCore.QRect(110, 460, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.c2.setFont(font)
        self.c2.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"")
        self.c2.setObjectName("c2")
        self.c3 = QtWidgets.QPushButton(self.centralwidget)
        self.c3.setGeometry(QtCore.QRect(200, 460, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.c3.setFont(font)
        self.c3.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 35px;\n"
"")
        self.c3.setObjectName("c3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.otv = ""
        self.show = "0"
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

        self.add_functions() 

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.answer.setText(_translate("MainWindow", self.show))
        self.AC.setText(_translate("MainWindow", "AC"))
        self.copy.setText(_translate("MainWindow", "❐"))
        self.delete.setText(_translate("MainWindow", "←"))
        self.share.setText(_translate("MainWindow", "÷"))
        self.mul.setText(_translate("MainWindow", "×"))
        self.c9.setText(_translate("MainWindow", "9"))
        self.c7.setText(_translate("MainWindow", "7"))
        self.c8.setText(_translate("MainWindow", "8"))
        self.minus.setText(_translate("MainWindow", "–"))
        self.c6.setText(_translate("MainWindow", "6"))
        self.c4.setText(_translate("MainWindow", "4"))
        self.c5.setText(_translate("MainWindow", "5"))
        self.equ.setText(_translate("MainWindow", "="))
        self.comma.setText(_translate("MainWindow", ","))
        self.c0.setText(_translate("MainWindow", "0"))
        self.c1.setText(_translate("MainWindow", "1"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.c2.setText(_translate("MainWindow", "2"))
        self.c3.setText(_translate("MainWindow", "3"))
    def add_functions(self):
                self.c0.clicked.connect(lambda: self.write_number("0")) 
                self.c1.clicked.connect(lambda: self.write_number("1")) 
                self.c2.clicked.connect(lambda: self.write_number("2")) 
                self.c3.clicked.connect(lambda: self.write_number("3")) 
                self.c4.clicked.connect(lambda: self.write_number("4")) 
                self.c5.clicked.connect(lambda: self.write_number("5")) 
                self.c6.clicked.connect(lambda: self.write_number("6")) 
                self.c7.clicked.connect(lambda: self.write_number("7")) 
                self.c8.clicked.connect(lambda: self.write_number("8")) 
                
                self.copy.clicked.connect(lambda: self.write_number("copy"))
                self.AC.clicked.connect(lambda: self.write_number("ac"))
                self.delete.clicked.connect(lambda: self.write_number("delete"))
                self.share.clicked.connect(lambda: self.write_number("/"))
                self.mul.clicked.connect(lambda: self.write_number("*"))
                self.minus.clicked.connect(lambda: self.write_number("-"))
                self.plus.clicked.connect(lambda: self.write_number("+"))
                self.equ.clicked.connect(lambda: self.write_number("equ"))
                self.comma.clicked.connect(lambda: self.write_number("."))
    def write_number(self, ev):
                if (self.otv == "error:(" or (self.show == "0" and self.otv == "")):    
                       if ev == "copy":
                              pass
                       else:
                                self.otv = ""
                                self.show = ""
                if (ev == "equ"):
                        try:
                              self.otv = str(round(eval(self.otv), 9))
                              if self.otv[len(self.otv)- 2:len(self.otv)] == ".0": 
                                     self.otv = self.otv[:-2]
                              self.show = self.otv
                              
                        except BaseException:
                              self.otv = "error:("
                              self.show = "error:("
                elif (ev == "ac"): 
                       self.otv = ""
                       self.show = "0"
                elif ev == "copy": 
                       pyperclip.copy(self.show)
                       
                elif ev == "delete": 
                       if (self.otv == ""):
                              pass
                       elif self.show[-1] == "." and len(self.otv) == 2:
                              self.otv = self.otv[:-1] 
                       elif self.show[-1] == "." and not (self.show[-2] in "0123456789"):
                              self.otv = self.otv[:-1] 
                       self.show = self.show[:-1]
                       self.otv = self.otv[:-1]
                       

                else: 
                        if ev == "." and len(self.otv) == 0:
                             self.otv += "0."
                             self.show += "."
                        elif ev == "." and self.otv[-1] in "+-*/":
                             self.otv += "0."
                             self.show += "."
                        elif ev in "*/.": 
                                if ev == ".": 
                                        flag = True
                                        for i in range (len(self.otv) - 1, -1, -1): 
                                                if self.otv[i] in  "+-/*": 
                                                        break
                                                if self.otv[i] == ".": 
                                                        flag = False
                                                        break 
                                        if flag == True:
                                               self.show += "."
                                               self.otv += "." 
                                else:
                                        flag = True
                                        for i in range(len(self.otv) - 1, -1, -1): 
                                               if (self.otv[i] in "*/"):
                                                      flag = False
                                                      break
                                               elif (self.otv[i] in "0123456789."):
                                                      break
                                        if flag == True:
                                                if ev == "/":
                                                        self.show += "÷"
                                                else:
                                                       self.show += "×"
                                                self.otv += ev
                        else:   
                               self.show += ev
                               self.otv += ev
                self.answer.setText(self.show)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
